// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import <Foundation/Foundation.h>
#import "PicoXMLClient.h"
#import "Trading_GeteBayOfficialTimeResponseType.h"
#import "Trading_GeteBayOfficialTimeRequestType.h"


/**
 This class is the XML client to the EBayAPIInterface Web Service.
*/ 
@interface EBayAPIInterface_XMLClient : PicoXMLClient {

}

/**
 public method
*/
-(void)geteBayOfficialTime:(Trading_GeteBayOfficialTimeRequestType *) requestObject 
      success:(void (^)(Trading_GeteBayOfficialTimeResponseType *responseObject))success
      failure:(void (^)(NSError *error))failure;


@end