// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import <Foundation/Foundation.h>
#import "PicoSOAPClient.h"
#import "Trading_GeteBayOfficialTimeResponseType.h"
#import "Trading_GeteBayOfficialTimeRequestType.h"


/**
 This class is the SOAP client to the EBayAPIInterface Web Service.
*/ 
@interface EBayAPIInterface_SOAPClient : PicoSOAPClient {

}

/**
 public method
*/
-(void)geteBayOfficialTime:(Trading_GeteBayOfficialTimeRequestType *) requestObject 
      success:(void (^)(Trading_GeteBayOfficialTimeResponseType *responseObject))success
      failure:(void (^)(NSError *error, id<PicoBindable> soapFault))failure;


@end