// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import "EBayAPIInterface_XMLClient.h"

@implementation EBayAPIInterface_XMLClient

-(void)geteBayOfficialTime:(Trading_GeteBayOfficialTimeRequestType *) requestObject 
      success:(void (^)(Trading_GeteBayOfficialTimeResponseType *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[Trading_GeteBayOfficialTimeResponseType class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}


@end