// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import "EBayAPIInterface_SOAPClient.h"

@implementation EBayAPIInterface_SOAPClient

-(void)geteBayOfficialTime:(Trading_GeteBayOfficialTimeRequestType *) requestObject 
      success:(void (^)(Trading_GeteBayOfficialTimeResponseType *responseObject))success
      failure:(void (^)(NSError *error, id<PicoBindable> soapFault))failure {
 
     [self.additionalParameters setObject: @"GeteBayOfficialTime" forKey: @"callname"];
     if(!requestObject.version) {
        requestObject.version = [self.additionalParameters objectForKey:@"version"];
     }
 
     [super invoke:requestObject responseClass:[Trading_GeteBayOfficialTimeResponseType class]
     success:^(PicoSOAPRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoSOAPRequestOperation *operation, NSError *error, id<PicoBindable> soapFault) {
         if (failure) {
             failure(error, soapFault);
         }
     }];
}


@end