// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

/**
   Common header file
*/

#import "Trading_DuplicateInvocationDetailsType.h"
#import "Trading_BotBlockRequestType.h"
#import "Trading_AbstractRequestType.h"
#import "Trading_GeteBayOfficialTimeResponseType.h"
#import "Trading_GeteBayOfficialTimeRequestType.h"
#import "Trading_BotBlockResponseType.h"
#import "Trading_ErrorParameterType.h"
#import "Trading_UserIdPasswordType.h"
#import "Trading_AbstractResponseType.h"
#import "Trading_ErrorType.h"
#import "Trading_CustomSecurityHeaderType.h"

#import "Trading_DetailLevelCodeType.h"
#import "Trading_ErrorHandlingCodeType.h"
#import "Trading_ErrorClassificationCodeType.h"
#import "Trading_InvocationStatusType.h"
#import "Trading_AckCodeType.h"
#import "Trading_SeverityCodeType.h"
#import "Trading_WarningLevelCodeType.h"
