// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import "EBayAPIInterface_XMLClient.h"

@implementation EBayAPIInterface_XMLClient

-(void)addToWatchList:(Trading_AddToWatchListRequestType *) requestObject 
      success:(void (^)(Trading_AddToWatchListResponseType *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[Trading_AddToWatchListResponseType class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}

-(void)getMyeBayBuying:(Trading_GetMyeBayBuyingRequestType *) requestObject 
      success:(void (^)(Trading_GetMyeBayBuyingResponseType *responseObject))success
      failure:(void (^)(NSError *error))failure {
 
 
     [super invoke:requestObject responseClass:[Trading_GetMyeBayBuyingResponseType class]
     success:^(PicoXMLRequestOperation *operation, id<PicoBindable> responseObject) {
         if (success) {
             success(responseObject);
         }
     } failure:^(PicoXMLRequestOperation *operation, NSError *error) {
         if (failure) {
             failure(error);
         }
     }];
}


@end